// examples/addfox-with-vue-tsx/app/popup/App.tsx
import { defineComponent, ref } from "vue";
import browser from "webextension-polyfill";

export default defineComponent({
  name: "PopupApp",
  setup() {
    const status = ref("Idle");

    async function pingBackground() {
      status.value = "Sending...";
      try {
        const res = await browser.runtime.sendMessage({ type: "PING" });
        status.value = res?.from === "background" ? "Background OK" : String(res);
      } catch (e) {
        status.value = "Error: " + (e as Error).message;
      }
    }

    async function sendToContent() {
      status.value = "Sending to content...";
      try {
        const res = await browser.runtime.sendMessage({
          type: "RELAY_TO_CONTENT",
          payload: { text: "Hello from popup at " + new Date().toISOString() },
        });
        status.value = typeof res === "object" ? "Content: " + JSON.stringify(res) : String(res);
      } catch (e) {
        status.value = "Error: " + (e as Error).message;
      }
    }

    return () => (
      <div class="popup">
        <h2>Vue TSX Popup</h2>
        <p>{status.value}</p>
        <button onClick={pingBackground}>Ping Background</button>
        <button onClick={sendToContent}>Send to Content</button>
      </div>
    );
  },
});

// examples/addfox-with-firefox-react/app/options/App.tsx
import { useState, useEffect } from "react";
import browser from "webextension-polyfill";

export default function App() {
  const [status, setStatus] = useState("Idle");
  const [nickname, setNickname] = useState("");

  useEffect(() => {
    browser.storage.sync.get("nickname").then((st) => {
      setNickname((st.nickname as string) || "");
    });
  }, []);

  async function pingBackground() {
    setStatus("Sending...");
    try {
      const res = await browser.runtime.sendMessage({ type: "PING" });
      setStatus(res?.from === "background" ? "Background OK" : String(res));
    } catch (e) {
      setStatus("Error: " + (e as Error).message);
    }
  }

  function save() {
    browser.storage.sync.set({ nickname });
    setStatus("Saved.");
  }

  return (
    <div style={{ padding: 24, fontFamily: "system-ui, sans-serif" }}>
      <h1 style={{ margin: "0 0 16px" }}>Firefox + React Options</h1>
      <p style={{ margin: "0 0 12px", color: "#666" }}>{status}</p>
      <button type="button" onClick={pingBackground} style={{ marginRight: 8, padding: "6px 12px", cursor: "pointer" }}>
        Ping Background
      </button>
      <div style={{ display: "flex", gap: 8, alignItems: "center", marginTop: 12 }}>
        <input
          type="text"
          placeholder="Nickname"
          value={nickname}
          onChange={(e) => setNickname(e.target.value)}
          style={{ flex: 1, padding: 6 }}
        />
        <button type="button" onClick={save} style={{ padding: "6px 12px", cursor: "pointer" }}>
          Save
        </button>
      </div>
    </div>
  );
}
