// examples/addfox-with-vue-tsx/app/popup/App.tsx
import { defineComponent, ref } from "vue";
import browser from "webextension-polyfill";

export default defineComponent({
  name: "PopupApp",
  setup() {
    const status = ref("Idle");

    async function pingBackground() {
      status.value = "Sending...";
      try {
        const res = await browser.runtime.sendMessage({ type: "PING" });
        status.value = res?.from === "background" ? "Background OK" : String(res);
      } catch (e) {
        status.value = "Error: " + (e as Error).message;
      }
    }

    async function sendToContent() {
      status.value = "Sending to content...";
      try {
        const res = await browser.runtime.sendMessage({
          type: "RELAY_TO_CONTENT",
          payload: { text: "Hello from popup at " + new Date().toISOString() },
        });
        status.value = typeof res === "object" ? "Content: " + JSON.stringify(res) : String(res);
      } catch (e) {
        status.value = "Error: " + (e as Error).message;
      }
    }

    return () => (
      <div class="popup">
        <h2>Vue TSX Popup</h2>
        <p>{status.value}</p>
        <button onClick={pingBackground}>Ping Background</button>
        <button onClick={sendToContent}>Send to Content</button>
      </div>
    );
  },
});

// examples/addfox-with-firefox-react/app/popup/App.tsx
import { useState } from "react";
import browser from "webextension-polyfill";

export default function App() {
  const [status, setStatus] = useState("Idle");

  async function pingBackground() {
    setStatus("Sending...");
    try {
      const res = await browser.runtime.sendMessage({ type: "PING" });
      setStatus(res?.from === "background" ? "Background OK" : String(res));
    } catch (e) {
      setStatus("Error: " + (e as Error).message);
    }
  }

  async function sendToContent() {
    setStatus("Sending to content...");
    try {
      const res = await browser.runtime.sendMessage({
        type: "RELAY_TO_CONTENT",
        payload: { text: "Hello from popup at " + new Date().toISOString() },
      });
      setStatus(typeof res === "object" ? "Content: " + JSON.stringify(res) : String(res));
    } catch (e) {
      setStatus("Error: " + (e as Error).message);
    }
  }

  return (
    <div style={{ width: 280, padding: 12, fontFamily: "system-ui, sans-serif" }}>
      <h2 style={{ margin: "0 0 8px", fontSize: 16 }}>Firefox + React Popup123</h2>
      <p style={{ margin: "0 0 12px", fontSize: 13, color: "#666" }}>{status}</p>
      <button type="button" onClick={pingBackground} style={{ marginRight: 8, marginBottom: 8, padding: "6px 12px", cursor: "pointer" }}>
        Ping Background
      </button>
      <button type="button" onClick={sendToContent} style={{ marginRight: 8, marginBottom: 8, padding: "6px 12px", cursor: "pointer" }}>
        Send to Content
      </button>
    </div>
  );
}
